### ISSUE TITLE
Buttons on home page no longer have square corners

### ISSUE THREAD

**Issue by talltom** [smart-facility/petajakarta-web#110]
Current home page:
<img width="953" alt="screen shot 2016-03-05 at 10 53 24 am" src="https://cloud.githubusercontent.com/assets/944642/13543570/8ea44606-e2c0-11e5-8a26-435bc85b16a4.png">

Should look like:
<img width="956" alt="screen shot 2016-03-05 at 10 59 40 am" src="https://cloud.githubusercontent.com/assets/944642/13543658/6665eec8-e2c1-11e5-8753-de6036a6cecf.png">

Previously buttons were forced to have square corners using "border-radius" CSS. Suspect this got lost/overridden after recent refactoring of CSS.

**Comment by matthewberryman** [comment]
Thing is, I prefer the new look. ;)

**Comment by talltom** [comment]
Its not the new look, its the old look ;) Design decision this year was to make all items square (you'll notice it on map buttons etc) as part of overall site theme.

**Comment by matthewberryman** [comment]
It's the new new look ;)

Yes I guess we had better be consistent.
