### ISSUE TITLE
On small screens the zoom controls are not positioned correctly

### ISSUE THREAD

**Issue by talltom** [smart-facility/petajakarta-web#113]
Previously, the map zoom controls were moved on small screens to account for changing size of navbar (i.e. y-axis position).

This bug can be replicated by resizing the window to emulate a small screen.

Bug is related to: #112 

<img width="335" alt="screen shot 2016-03-05 at 11 03 47 am" src="https://cloud.githubusercontent.com/assets/944642/13543760/7cfc43ac-e2c2-11e5-995f-fa1f7f289219.png">

**Comment by matthewberryman** [comment]
See my comments on #112 but this one doesn't apply to iOS mobile devices at all since zoom controls are not shown in favour of users using pinch to zoom.

**Comment by talltom** [comment]
@matthewberryman - yes this is only shown for non-touch screen devices.
