### ISSUE TITLE
Data API Documentation needs updating for flooded states

### ISSUE THREAD

**Issue by talltom** [smart-facility/petajakarta-web#117]
* last_updated field added to JSON output
* minimum_states parameter added to query,

both need to be documented on the data page.

**Comment by talltom** [comment]
Also - did @benatwork99 fix a bug which was stopping pushing of "null" to flood state parameter? Either way need to update docs around different of "null" and "0" in state parameter.

**Comment by benatwork99** [comment]
Yes I believe this was the fix:

https://github.com/smart-facility/cognicity-rem-server/commit/6a8199aa532c36e4bbabd8177a6d22f8ae39fa89#diff-4edd374f0e639d2565b60300447bb8b5L241
