### ISSUE TITLE
Map flood sensor data

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/petajakarta-web#122]
* Water depth.
* Temperature (if available on device).
* Humidity (if available on device).
* Update API page with appropriate documentation

**Comment by talltom** [comment]
See new IoT branch for progress - sensors now on map, next step is to build graph.

**Comment by matthewberryman** [comment]
Done in https://github.com/smart-facility/petajakarta-web/commit/9a9bfd0e15a7ef44fbff7236408d44ddd2d124e1
