### ISSUE TITLE
No Waterlevel live on PetaJakarta Map?

### ISSUE THREAD

**Issue by fadmastuti** [smart-facility/petajakarta-web#126]
<img width="1425" alt="screen shot 2016-11-07 at 11 53 05 am" src="https://cloud.githubusercontent.com/assets/2441950/20046831/ca50ba62-a4e0-11e6-9e2e-1b1ddac4ffcc.png">

No river gauge is shown on the map.

**Comment by matthewberryman** [comment]
The server that provides floodgauge data to us is down. Please contact BPBD.
