### ISSUE TITLE
change tense

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/petajakarta-web#128]
/is/was/ on index page

**Comment by matthewberryman** [comment]
@talltom not sure how much we care about this, or ID translation thereof

**Comment by tomasholderness** [comment]
@matthewberryman - propose keeping all original site text as was for records and simplicity and relying on additional text info I added to inform the user that the project no longer/active. That make sense?

**Comment by matthewberryman** [comment]
Ok, was just flagging it.
