### ISSUE TITLE
decide on default language

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/petajakarta-web#129]
We're going to host static branch statically, so we can't rely on node detecting browser language

**Comment by tomasholderness** [comment]
Indonesian should be default. What do you think is best method to set the default for static hosting?

**Comment by matthewberryman** [comment]
I will just point the root object at the Indonesian page and then users can select English from there.

**Comment by matthewberryman** [comment]
Deploying this change to CloudFront now (may take a little while before all users can see the change).
