### ISSUE TITLE
Aggregate overview contains sliver polygons

### ISSUE THREAD

**Issue by talltom** [smart-facility/petajakarta-web#29]
Boundary mismatches at different scales. See eastern Jakarta in attached screenshot.

![Screenshot showing sliver polygons][ss]
[ss]: https://raw.githubusercontent.com/wiki/smart-facility/petajakarta-web/images/screenshots/desktop_firefox.png

**Comment by talltom** [comment]
See also #66

**Comment by matthewberryman** [comment]
@talltom let's fix the original issue here (sorry for the dupe)

**Comment by talltom** [comment]
Aggregate layers have been removed in v2.0.
