### ISSUE TITLE
Pages describing API should refer to v2

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/petajakarta-web#56]
Pages describing the API should refer to URLs for v2 of the API in [cognicity-server](http://github.com/smart-facility/cognicity-server).

**Comment by talltom** [comment]
@matthewberryman 
- API URLS in branch 1.0.x should be left as is. 
- API URLS in branch 2.0.x should be updated as you say. 

Note that there is already an internal development item for this, which I have now linked to this issue.

**Comment by matthewberryman** [comment]
There are still some references in the site code as well as the on-site docs that need changing, e.g. https://github.com/smart-facility/petajakarta-web/blob/2.0.x/banjir/assets/js/analytics.js#L29
I will fix those also.

**Comment by matthewberryman** [comment]
@talltom and @benatwork99 we still need to bear this in mind when writing new docs about additions to v2 api but this particular issue is now resolved.

**Comment by talltom** [comment]
Yep. Requirements for all this already listed on Trello. Don't see need to task this kind of development as a "bug".
