### ISSUE TITLE
slow colour map loading

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/petajakarta-web#63]
To reproduce:
Select appropriate zoom level (v1) / unconfirmed map (v2). Select a different time window (e.g. switch from 1 hr to 3 hrs). Loses the colour map temporarily. Could we speed this up? I am not sure if this is a bug in the client or server side js.

**Comment by talltom** [comment]
Changing the temporal duration (i.e. from 1 to 2 hours) triggers a new request to cognicity-server for data. The time taken to change the layer is a function of network speed and map.js to unpack data, and Leaflet to render.

2f6539c adds a spinner notification whilst the layers are changing to help improve UI.

Note that for v2.0 aggregates will be moved to separate analytics page, and won't be featured on the main map.

**Comment by matthewberryman** [comment]
Ok. I will take a quick squiz at map.js tomorrow and see if there are low hanging fruit and if not then close.

**Comment by talltom** [comment]
@matthewberryman - As we're no longer providing option of different time durations/aggregate data I think this can be closed?
