### ISSUE TITLE
Dynamically set report popup size depending on screen resolution and report size

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/petajakarta-web#64]
They take up a lot of screen real estate, particularly on a mobile device. ![image](https://cloud.githubusercontent.com/assets/2288238/11203152/ed78a644-8d44-11e5-8b93-56adad77cb6e.jpeg)

**Comment by talltom** [comment]
Note that fixed popup size also cauese a problem when the tweet is very small (i.e. no media embedded). Ideally should be a combinaton of dynamic sizing based on tweet and screensize

<img width="355" alt="screen shot 2015-11-24 at 1 51 26 pm" src="https://cloud.githubusercontent.com/assets/944642/11359877/a4f751b8-92b2-11e5-8335-5a487f87b46e.png">

**Comment by talltom** [comment]
Widths of tweets are fixed, but I've managed to get size down to 220px and shrunk detik reports in line with this also.
