### ISSUE TITLE
Placement of logos could be improved

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/petajakarta-web#67]
The layout is a bit all over the place on mobile devices. Thanks to @tim-davies for spotting this.
![simulator screen shot 19 nov 2015 13 33 34](https://cloud.githubusercontent.com/assets/2288238/11260797/85faf6f0-8ec2-11e5-9c07-28fe511f20c0.png)

**Comment by talltom** [comment]
This was fixed by 91f402c9b0fa2044e84ac8f3513c90b1bd822b85, so I'm going to close this issue.
