### ISSUE TITLE
Duplicate times in floodgauge charts

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/petajakarta-web#70]
![image](https://cloud.githubusercontent.com/assets/2288238/11599184/758c229a-9b19-11e5-844c-4cc428eda401.jpeg)

**Comment by matthewberryman** [comment]
[db_and_logs.zip](https://github.com/smart-facility/petajakarta-web/files/52516/db_and_logs.zip)

**Comment by talltom** [comment]
Pushed a fix to cognicity-reports-floodgauges, where timezone was set wrong and SQL rows loop was incorrect. 

https://github.com/smart-facility/cognicity-reports-floodgauge/commit/b59b95077521f1e521fa4be8e4d88c52b1955776

**Comment by matthewberryman** [comment]
I have this running on dev. Will monitor (ignoring old data that I won't drop). You can bump cognicity-reports to have updated submodule if you like but I'm primarily focussing on the merge branch of cognicity-reports.

**Comment by matthewberryman** [comment]
Still not quite right. 
![screenshot 2015-12-05 15 31 21](https://cloud.githubusercontent.com/assets/2288238/11606019/47631ada-9b65-11e5-8df2-c2b8ec4c517d.png)

**Comment by matthewberryman** [comment]
@talltom looking at it coming in, it looks like you might be omitting the minutes when displaying?

**Comment by talltom** [comment]
Check out latest pushes to floodgauge submodule. It was a problem with check for duplicate data.

https://github.com/smart-facility/cognicity-reports-floodgauge/commits/master

**Comment by matthewberryman** [comment]
Giving that a whirl now.

**Comment by matthewberryman** [comment]
The graph is now broken (numbers not entirely visible on both axes and the x-axis having way too many data points)
![image](https://cloud.githubusercontent.com/assets/2288238/11609790/6eb41c90-9be4-11e5-8ea9-4481798dec6d.jpeg)

**Comment by matthewberryman** [comment]
Hard for me to check until either #72 is fixed or I could drop the tables and recreate if you like ?

**Comment by matthewberryman** [comment]
Seems to be resolving as new data comes in. Happy to close this off.
