### ISSUE TITLE
Floodgauge chart showing too much data

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/petajakarta-web#72]
The chart shows too much data, resulting in numbers being cut off in scales for both axes, and a cluttered x-axis scale. This is I believe independent of the duplicate data bug #70 as it would be still present once you've collected enough data.
![image](https://cloud.githubusercontent.com/assets/2288238/11609832/69ad9de2-9be5-11e5-9e74-6358ba242bd3.jpeg)

**Comment by matthewberryman** [comment]
Looking back at #70 screenshots, the scale on the y axis is cut off there too, even with a reasonable amount of data points.

**Comment by talltom** [comment]
The cut off problem is now fixed (it was a formatting issue).

Note that now the duplicate report bug is also fixed (#70), graphs should show a maximum of 12 hours worth of reports (which should fit reasonably within the graph). This value is controled by the cognicity-server config parameter `config.api.floodgauges.time_window`

Given its the weekend, if we leave the floodgauges reports module running (which it appears to be) you should notice complete fixes on the graphs over the next 8 hours or so, whilst the remaining duplicate reports are cleared from the API.

**Comment by matthewberryman** [comment]
Ok I am happy to close this then. It's starting to look better now for this and for #70 on iPhone, will check with iPad but behaviour should be better there too.
