### ISSUE TITLE
Colours for flood levels

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/petajakarta-web#89]
Colours need to be changed as follows (written ranges fixed in #88).

       / Hati Hati       Blue

        / 10 – 70cm    Yellow

        / 71 – 150cm   Orange

        / 151cm +       Red

**Comment by talltom** [comment]
/ No data yet      Purple
![flood_heigh_classification](https://cloud.githubusercontent.com/assets/944642/12708352/c0b5a4ce-c8f2-11e5-883f-397cccf492dd.png)

**Comment by talltom** [comment]
```html
<p style="color:'red'">red</p>
```

**Comment by talltom** [comment]
Interpreted colours are as follows:
* > 150 cm Hex: #FF0000
* 71 - 150 cm Hex: #FFA740
* 10 - 70 cm Hex: #FFE556
* Hati-hati Hex: #A0A9F7

**Comment by talltom** [comment]
Fixed in 0bf33237132d09eaf794d27be5d21d6f37badf91
