### ISSUE TITLE
Icons cropped in IE

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/petajakarta-web#91]
![image](https://cloud.githubusercontent.com/assets/2288238/12878119/088a058a-ce73-11e5-9271-a3da4eb02822.png)

**Comment by benatwork99** [comment]
The flood gauge icons (and some others) are SVG files. IE has a number of issues rendering SVG files, rasterizing these SVGs is probably going to be the simplest (and most browser-compatible) way to fix this.

**Comment by benatwork99** [comment]
@matthewberryman @talltom Are you guys happy if I go ahead and create PNGs and we use them instead of the SVG?

**Comment by matthewberryman** [comment]
Yes
