### ISSUE TITLE
Map.js - getREM doesn't make use of TopoJSON

### ISSUE THREAD

**Issue by talltom** [smart-facility/petajakarta-web#95]
Increases load time of petajakarta.org between 0.5 and 1 second.

https://github.com/smart-facility/petajakarta-web/blob/master/banjir/assets/js/map.js#L246

Need to add:
```javascript
callback(topojson.feature(data, data.objects.collection));

```

**Comment by matthewberryman** [comment]
@talltom I'm also going to have a separate look at caching rules as well.

**Comment by talltom** [comment]
@matthewberryman - cool, I've closed this, as just pushed updated. Will deploy shortly.

But, perhaps take a look at cache on rem-server? Chrome profiling indicates that TTFB when polling REM API is longest component in loading this data (FYI screenshot running on local host, but connecting to REM on prod).

<img width="1276" alt="screen shot 2016-02-10 at 10 05 02 am" src="https://cloud.githubusercontent.com/assets/944642/12933775/01e3838e-cfde-11e5-916b-c9df8057f3a3.png">

**Comment by matthewberryman** [comment]
Yes that's what I meant.
